fix syntax, add emojis

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -71,25 +71,23 @@ jobs:
           twine upload -u $PYPI_USER -p $PYPI_PASS dist/*
       - name: Wait up to 3 minutes for PyPi availability
         run: |
-          pwd
-          ls -la
           export VER=$(cat VERSION)
           export VER=${VER#"v"}
-          export PIPERR=$(pip install runnow==versioncheck 2>&1)
+          export PIPERR="$(pip install runnow==versioncheck 2>&1)"
           echo "Checking for PyPi availability of version $VER"
-          if [[ $PIPERR == *"$VER"* ]]; then { echo "Yes"; } else { echo "Not yet found..."; sleep 30; } fi;
-          export PIPERR=$(pip install runnow==versioncheck 2>&1)
-          if [[ $PIPERR == *"$VER"* ]]; then { echo "Yes"; } else { echo "Not yet found..."; sleep 30; } fi;
-          export PIPERR=$(pip install runnow==versioncheck 2>&1)
-          if [[ $PIPERR == *"$VER"* ]]; then { echo "Yes"; } else { echo "Not yet found..."; sleep 30; } fi;
-          export PIPERR=$(pip install runnow==versioncheck 2>&1)
-          if [[ $PIPERR == *"$VER"* ]]; then { echo "Yes"; } else { echo "Not yet found..."; sleep 30; } fi;
-          export PIPERR=$(pip install runnow==versioncheck 2>&1)
-          if [[ $PIPERR == *"$VER"* ]]; then { echo "Yes"; } else { echo "Not yet found..."; sleep 30; } fi;
-          export PIPERR=$(pip install runnow==versioncheck 2>&1)
-          if [[ $PIPERR == *"$VER"* ]]; then { echo "Yes"; } else { echo "Not yet found..."; sleep 30; } fi;
-          export PIPERR=$(pip install runnow==versioncheck 2>&1)
-          if [[ $PIPERR == *"$VER"* ]]; then { echo "Yes"; } else { echo "Not found. Giving up. Last message from PyPi was $PIPERR"; exit 1; } fi;      - name: Test install (pip install runnow)
+          if [[ $PIPERR == *"$VER"* ]]; then { echo "Availability confirmed 👍"; } else { echo "Not yet found..."; sleep 30; } fi;
+          export PIPERR="$(pip install runnow==versioncheck 2>&1)"
+          if [[ $PIPERR == *"$VER"* ]]; then { echo "Availability confirmed 👍"; } else { echo "Not yet found..."; sleep 30; } fi;
+          export PIPERR="$(pip install runnow==versioncheck 2>&1)"
+          if [[ $PIPERR == *"$VER"* ]]; then { echo "Availability confirmed 👍"; } else { echo "Not yet found..."; sleep 30; } fi;
+          export PIPERR="$(pip install runnow==versioncheck 2>&1)"
+          if [[ $PIPERR == *"$VER"* ]]; then { echo "Availability confirmed 👍"; } else { echo "Not yet found..."; sleep 30; } fi;
+          export PIPERR="$(pip install runnow==versioncheck 2>&1)"
+          if [[ $PIPERR == *"$VER"* ]]; then { echo "Availability confirmed 👍"; } else { echo "Not yet found..."; sleep 30; } fi;
+          export PIPERR="$(pip install runnow==versioncheck 2>&1)"
+          if [[ $PIPERR == *"$VER"* ]]; then { echo "Availability confirmed 👍"; } else { echo "Not yet found..."; sleep 30; } fi;
+          export PIPERR="$(pip install runnow==versioncheck 2>&1)"
+          if [[ $PIPERR == *"$VER"* ]]; then { echo "Availability confirmed 👍"; } else { echo "Not found. Giving up. Last message from PyPi was $PIPERR"; exit 1; } fi;
       - name: Test install (pip install runnow)
         run: |
           pip install --no-cache-dir runnow==$(cat VERSION)
